HOST = "localhost"
PORT = 5433
USER = "user"
PASSWORD = "password1234"
DB_NAME = "natural_event_db"
DEFAULT_SCHEMA =  "public"
DEFAULT_CONTAINER = "database_service"
COMPOSE_FILE_PATH = "DockerCompose.yml"
TEMPLATES_PATH = "templates/"
HTMLS_PATH = "templates/"
# SQL Queries
ALL_EVENTS = "SELECT * FROM natural_event"
ALL_TORNADOES = "SELECT * FROM tornado_trace"
#columns
YEAR = "event_year"
MONTH = "event_month"
DAY = "event_day"
EVENT_TYPE = "event_type"
COUNTRY = "country"
LONGITUDE = "longitude"
LATITUDE = "latitude"
REGION = "region"
NATURAL_EVENT_ID = "natural_event_id"
LONGITUDE_END = "longitudeend"
LATITUDE_END = "latitudeend"